### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Alexxxx3421** [JOY6IX9INE/OperaGX-Discord-Promo-Gen#10]
Links not working and I just made this account and generated this link
https://cdn.discordapp.com/attachments/1175875169705791608/1187514750838509588/image.png?ex=65972a4b&is=6584b54b&hm=27ff36595aad1184cfcfd32b75778a5df2a4f3fbe73f9b5a71665a374ef7d5b0&

**Comment by DenisDziganchuk** [comment]
Unless you have not redeemed any promotion or didn't have Discord Nitro in the past 12 months, you can't redeem it, unfortunately. The same is true for any promotion done by Discord.
