### ISSUE TITLE
Request failed : 403

### ISSUE THREAD

**Issue by alchemist444** [JOY6IX9INE/OperaGX-Discord-Promo-Gen#13]
Good morning. The generator is giving a Request Failed error. Could you solve this problem? <3

**Comment by just-rich** [comment]
I'm getting same, so it either doesn't work anymore or proxies are required- I wasn't using any.

**Comment by louanfontenele** [comment]
Same here:

![image](https://github.com/JOY6IX9INE/OperaGX-Discord-Promo-Gen/assets/2886066/24e676e6-1d46-4533-9046-7403bea24002)

**Comment by just-rich** [comment]
I know the Discord Nitro trial is still active with Opera, because you can install the browser and claim it still.

Any time I used this tool though, if I didn't use all the Nitro links within the same day they would be disabled when I tried to use them again.

**Comment by JOY6IX9INE** [comment]
I have updated the code, now it's working fine!
