### ISSUE TITLE
GetAddrInfoFailes

### ISSUE THREAD

**Issue by ayaanmd100** [JOY6IX9INE/OperaGX-Discord-Promo-Gen#17]
GetAddrInfoFailes
No such domain as "api.discord.gx.games"

**Comment by JOY6IX9INE** [comment]
![image](https://github.com/JOY6IX9INE/OperaGX-Discord-Promo-Gen/assets/95956256/8d3857d3-868b-406e-94b5-e482844cec23)
Its patched, i have already mentioned
