### ISSUE TITLE
If you are looking for this, READ THIS NOW

### ISSUE THREAD

**Issue by NoobToolzz** [JOY6IX9INE/OperaGX-Discord-Promo-Gen#3]
As the README says, this version has been patched. However, I had been making a separate version of this that uses Opera GX chromium driver to claim the promotion links and output them to a file rather than messing around with the API.

I don't think this will be patched, if it does, not as fast as this. I suggest not using more than one thread as it kills your CPU and your PC will to put it simply, not feel okay. You can find mine [here](https://github.com/NoobToolzz/OperaGX-Discord-Promocode-Generator). Don't forget to star it!

Enjoy!

**Comment by JOY6IX9INE** [comment]
No This Is Not Patched!

**Comment by NoobToolzz** [comment]
> No This Is Not Patched!

Wait, last time I saw this it said patched. Oh well, that's good.
