### ISSUE TITLE
Where to get FREE username:password@host:port proxys?

### ISSUE THREAD

**Issue by Fr0go1** [JOY6IX9INE/OperaGX-Discord-Promo-Gen#6]

**Comment by JOY6IX9INE** [comment]
Idk 💀

**Comment by JOY6IX9INE** [comment]
you can just buy from somewhere

**Comment by Fr0go1** [comment]
> you can just buy from somewhere

do you know any sites?

**Comment by JOY6IX9INE** [comment]
https://www.webshare.io/

**Comment by Fr0go1** [comment]
> https://www.webshare.io/

would oyu be able to create a branch or something that uses socks4 or socks5 instead?

**Comment by XxGhost280xX** [comment]
Webshare gives 10 free proxies (HTTPS/Socks4-5)
