### ISSUE TITLE
nitro cannot be redeemed

### ISSUE THREAD

**Issue by Rawi1005** [JOY6IX9INE/OperaGX-Discord-Promo-Gen#7]
![image](https://github.com/JOY6IX9INE/OperaGX-Discord-Promo-Gen/assets/101038560/03e7fa71-d406-4011-92b9-e8145f458655)

**Comment by JOY6IX9INE** [comment]
probably discord patched the nitro links 💀
also stop complaining on what you got for free!
the code is open source you can check it out yourself if there is something.

**Comment by Rawi1005** [comment]
i know that lmao i have been written my own code for 3 days too lmao i just finding if i am only one who got discord patced btw thanks for the response
